/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v3.0.0), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 100 }

  type BasicWhereableFromInsertable<T> = { [K in keyof T]: Exclude<T[K] | db.ParentColumn, null | db.DefaultType> };
  type WhereableFromBasicWhereable<T> = { [K in keyof T]?: T[K] | db.SQLFragment<any, T[K]> };
  type WhereableFromInsertable<T> = WhereableFromBasicWhereable<BasicWhereableFromInsertable<T>>;

  type UpdatableFromInsertable<T> = { [K in keyof T]?: T[K] | db.SQLFragment<any, T[K]> };

  type JSONSelectableFromSelectable<T> = { [K in keyof T]:
    Date extends T[K] ? Exclude<T[K], Date> | db.DateString :
    Date[] extends T[K] ? Exclude<T[K], Date[]> | db.DateString[] :
    T[K]
  };

  /* === schema: public === */

  /* --- enums --- */


  /* --- tables --- */

  export namespace User {
    export type Table = 'User';
    export interface Selectable {
      id: number;
      name: string;
    }
    export interface Insertable {
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      name: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable extends UpdatableFromInsertable<Insertable> { }
    export interface Whereable extends WhereableFromInsertable<Insertable> { }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'User_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* === cross-table types === */

  export type Table = User.Table;
  export type Selectable = User.Selectable;
  export type Whereable = User.Whereable;
  export type Insertable = User.Insertable;
  export type Updatable = User.Updatable;
  export type UniqueIndex = User.UniqueIndex;
  export type Column = User.Column;
  export type AllTables = [User.Table];


  export type SelectableForTable<T extends Table> = {
    User: User.Selectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    User: User.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    User: User.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    User: User.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    User: User.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    User: User.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    User: User.SQL;
  }[T];

}
