/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v3.0.0), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 100 }

  type BasicWhereableFromInsertable<T> = { [K in keyof T]: Exclude<T[K] | db.ParentColumn, null | db.DefaultType> };
  type WhereableFromBasicWhereable<T> = { [K in keyof T]?: T[K] | db.SQLFragment<any, T[K]> };
  type WhereableFromInsertable<T> = WhereableFromBasicWhereable<BasicWhereableFromInsertable<T>>;

  type UpdatableFromInsertable<T> = { [K in keyof T]?: T[K] | db.SQLFragment<any, T[K]> };

  type JSONSelectableFromSelectable<T> = { [K in keyof T]:
    Date extends T[K] ? Exclude<T[K], Date> | db.DateString :
    Date[] extends T[K] ? Exclude<T[K], Date[]> | db.DateString[] :
    T[K]
  };

  /* === schema: public === */

  /* --- enums --- */


  /* --- tables --- */

  export namespace Follow {
    export type Table = 'Follow';
    export interface Selectable {
      followerId: number;
      followeeId: number;
      createdAt: Date | null;
    }
    export interface Insertable {
      followerId: number | db.Parameter<number> | db.SQLFragment;
      followeeId: number | db.Parameter<number> | db.SQLFragment;
      createdAt?: Date | db.Parameter<Date> | db.DateString | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable extends UpdatableFromInsertable<Insertable> { }
    export interface Whereable extends WhereableFromInsertable<Insertable> { }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'Follow_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace Hashtag {
    export type Table = 'Hashtag';
    export interface Selectable {
      id: number;
      text: string;
    }
    export interface Insertable {
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      text: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable extends UpdatableFromInsertable<Insertable> { }
    export interface Whereable extends WhereableFromInsertable<Insertable> { }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'Hashtag_pkey' | 'Hashtag_text_key';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace Like {
    export type Table = 'Like';
    export interface Selectable {
      twitId: number;
      userId: number;
    }
    export interface Insertable {
      twitId: number | db.Parameter<number> | db.SQLFragment;
      userId: number | db.Parameter<number> | db.SQLFragment;
    }
    export interface Updatable extends UpdatableFromInsertable<Insertable> { }
    export interface Whereable extends WhereableFromInsertable<Insertable> { }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'Like_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace Twit {
    export type Table = 'Twit';
    export interface Selectable {
      id: number;
      text: string;
      createdAt: Date | null;
      authorId: number;
    }
    export interface Insertable {
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      text: string | db.Parameter<string> | db.SQLFragment;
      createdAt?: Date | db.Parameter<Date> | db.DateString | null | db.DefaultType | db.SQLFragment;
      authorId: number | db.Parameter<number> | db.SQLFragment;
    }
    export interface Updatable extends UpdatableFromInsertable<Insertable> { }
    export interface Whereable extends WhereableFromInsertable<Insertable> { }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'Twit_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace Twit_Hashtag {
    export type Table = 'Twit_Hashtag';
    export interface Selectable {
      twitId: number;
      hashtagId: number;
    }
    export interface Insertable {
      twitId: number | db.Parameter<number> | db.SQLFragment;
      hashtagId: number | db.Parameter<number> | db.SQLFragment;
    }
    export interface Updatable extends UpdatableFromInsertable<Insertable> { }
    export interface Whereable extends WhereableFromInsertable<Insertable> { }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'Twit_Hashtag_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  export namespace User {
    export type Table = 'User';
    export interface Selectable {
      id: number;
      username: string;
      password: string;
      createdAt: Date | null;
    }
    export interface Insertable {
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      username: string | db.Parameter<string> | db.SQLFragment;
      password: string | db.Parameter<string> | db.SQLFragment;
      createdAt?: Date | db.Parameter<Date> | db.DateString | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable extends UpdatableFromInsertable<Insertable> { }
    export interface Whereable extends WhereableFromInsertable<Insertable> { }
    export interface JSONSelectable extends JSONSelectableFromSelectable<Selectable> { }
    export type UniqueIndex = 'User_pkey' | 'User_username_key';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* === cross-table types === */

  export type Table = Follow.Table | Hashtag.Table | Like.Table | Twit.Table | Twit_Hashtag.Table | User.Table;
  export type Selectable = Follow.Selectable | Hashtag.Selectable | Like.Selectable | Twit.Selectable | Twit_Hashtag.Selectable | User.Selectable;
  export type Whereable = Follow.Whereable | Hashtag.Whereable | Like.Whereable | Twit.Whereable | Twit_Hashtag.Whereable | User.Whereable;
  export type Insertable = Follow.Insertable | Hashtag.Insertable | Like.Insertable | Twit.Insertable | Twit_Hashtag.Insertable | User.Insertable;
  export type Updatable = Follow.Updatable | Hashtag.Updatable | Like.Updatable | Twit.Updatable | Twit_Hashtag.Updatable | User.Updatable;
  export type UniqueIndex = Follow.UniqueIndex | Hashtag.UniqueIndex | Like.UniqueIndex | Twit.UniqueIndex | Twit_Hashtag.UniqueIndex | User.UniqueIndex;
  export type Column = Follow.Column | Hashtag.Column | Like.Column | Twit.Column | Twit_Hashtag.Column | User.Column;
  export type AllTables = [Follow.Table, Hashtag.Table, Like.Table, Twit.Table, Twit_Hashtag.Table, User.Table];


  export type SelectableForTable<T extends Table> = {
    Follow: Follow.Selectable;
    Hashtag: Hashtag.Selectable;
    Like: Like.Selectable;
    Twit: Twit.Selectable;
    Twit_Hashtag: Twit_Hashtag.Selectable;
    User: User.Selectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    Follow: Follow.Whereable;
    Hashtag: Hashtag.Whereable;
    Like: Like.Whereable;
    Twit: Twit.Whereable;
    Twit_Hashtag: Twit_Hashtag.Whereable;
    User: User.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    Follow: Follow.Insertable;
    Hashtag: Hashtag.Insertable;
    Like: Like.Insertable;
    Twit: Twit.Insertable;
    Twit_Hashtag: Twit_Hashtag.Insertable;
    User: User.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    Follow: Follow.Updatable;
    Hashtag: Hashtag.Updatable;
    Like: Like.Updatable;
    Twit: Twit.Updatable;
    Twit_Hashtag: Twit_Hashtag.Updatable;
    User: User.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    Follow: Follow.UniqueIndex;
    Hashtag: Hashtag.UniqueIndex;
    Like: Like.UniqueIndex;
    Twit: Twit.UniqueIndex;
    Twit_Hashtag: Twit_Hashtag.UniqueIndex;
    User: User.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    Follow: Follow.Column;
    Hashtag: Hashtag.Column;
    Like: Like.Column;
    Twit: Twit.Column;
    Twit_Hashtag: Twit_Hashtag.Column;
    User: User.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    Follow: Follow.SQL;
    Hashtag: Hashtag.SQL;
    Like: Like.SQL;
    Twit: Twit.SQL;
    Twit_Hashtag: Twit_Hashtag.SQL;
    User: User.SQL;
  }[T];

}
